### PR TITLE
fixes #50 - Laravel 5.6.24 renamed function

### LINKED ISSUE #50: onOneServer schedules cause exception
Call to undefined method Illuminate\Console\Scheduling\Schedule::allowServerToRun()
at /vendor/eyewitness/eye/app/Commands/Framework/ScheduleRunCommand.php:27

This method was renamed in this commit:
https://github.com/laravel/framework/commit/6563ba65b65106198095f1d61f91e0ec542e98dd#diff-0de50829a544cd21193aef291b5a9baf

### PR DESCRIPTION
**Pull request by glamorous**
This fixes #50. The function allowServerToRun in the scheduler was renamed so this fails en no crons for one server are called. The code in the command was refactored in laravel/framework@6563ba6#diff-0de50829a544cd21193aef291b5a9baf so the new created function could be used here too.

### CODE REVIEW

**Comment by laurencei** [comment]
Awesome. Thanks @glamorous

**Comment by glamorous** [comment]
@laurencei Will you create a new release with all the latest fixes?

**Comment by laurencei** [comment]
@glamorous - as this is the "beta" branch - I think should always pull the latest commit if you run `composer update` (as it was installed from the beta branch)?

**Comment by glamorous** [comment]
Indeed, my bad! 👍

**Pull request merged**
