### PR TITLE
Support Auto-Discovery

### PR DESCRIPTION
**Pull request by m1guelpf**
This will make the package work with [auto-discovery](https://github.com/laravel/framework/pull/19420) in Laravel 5.5

### CODE REVIEW

**Comment by laurencei** [comment]
Thanks @m1guelpf 

I was holding off this PR for the moment, because some initial testing suggests we might be not able to use the auto-discovery feature.

However a recent PR here https://github.com/laravel/framework/pull/19646 seems to fix it.

I'll do some more testing, then hopefully merge shortly.

**Comment by m1guelpf** [comment]
The PR you linked is merged, can you merge this now?

**Comment by laurencei** [comment]
I'm literally running some final tests now - should be merged in a few minutes if no issues :)

**Comment by laurencei** [comment]
Thanks @m1guelpf

**Pull request merged**
